services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - "5444:5432"

  bakery:
    image: bakery.startup
    build:
      context: .
      dockerfile: Bakery.Startup/Dockerfile
    ports:
      - "8080:8080"
        
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${APPDATA}/ASP.NET/https:/https:ro
    depends_on:
      - bakery
